name: Test PortAudio binaries
on: [push, pull_request]
jobs:
  binaries:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: 'arm64'
          # Last version with Intel CPU:
          - os: macos-13
            arch: 'x64'
          - os: windows-latest
            arch: 'x64'
          - os: windows-latest
            arch: 'x86'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: ${{ matrix.arch }}
      - name: Double-check Python version
        run: |
          python --version
      - name: Clone Git repository (with submodules)
        uses: actions/checkout@v4
        with:
          path: git-repo
          submodules: true
      - name: Install Python package
        working-directory: git-repo
        run: |
          python -m pip install .
      - name: Run tests
        run: |
          python -m sounddevice
          python -c "import sounddevice as sd; print(sd._libname)"
          python -c "import sounddevice as sd; print(sd.get_portaudio_version())"
